[project]
name = "auto-catalog-ai"
version = "0.1.0"
description = "AutoCatalogAI is an AI-powered solution that leverages computer vision to analyze vehicle images, generate metadata, and automate database structuring for web catalogs."
authors = [
    {name = "Alejandro Mantilla",email = "alejandromantilla7@hotmail.com"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.115.8,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
